version: "2.17"

services:
  planning-control:
    image: ghcr.io/autowarefoundation/autoware-openadk:latest-planning-control
    volumes:
      - /dev/shm:/dev/shm
      - ${MAP_PATH}:/autoware/map/
    network_mode: "host"
    environment:
      - ROS_LOCALHOST_ONLY=1
    command: ros2 launch launch/planning_control.launch.xml vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit map_path:=/autoware/map/ rviz:=false

  perception-localization:
    image: ghcr.io/autowarefoundation/autoware:latest-perception-localization
    volumes:
      - /dev/shm:/dev/shm
      - ${MAP_PATH}:/autoware/map/
    network_mode: "host"
    environment:
      - ROS_LOCALHOST_ONLY=1
    command: ros2 launch launch/perception_localization.launch.xml vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit map_path:=/autoware/map/ perception/enable_traffic_light:=false rviz:=false

  simulator:
    image: ghcr.io/autowarefoundation/autoware-openadk:latest-simulator
    volumes:
      - /dev/shm:/dev/shm
      - ${MAP_PATH}:/autoware/map/
    network_mode: "host"
    environment:
      - ROS_LOCALHOST_ONLY=1
    depends_on:
      - planning-control
    command: ros2 launch autoware_launch logging_simulator.launch.xml map_path:=/autoware/map/ vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit rviz:=false

  visualizer:
    image: ghcr.io/autowarefoundation/autoware-openadk:latest-visualizer
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      - ROS_LOCALHOST_ONLY=1
    depends_on:
      - simulator
    command: ros2 launch/visualizer.launch.xml rviz:=true
